theme = "catppuccin_custom"

[editor]
line-number = "relative"
cursor-shape = { insert = "bar" }
bufferline = "never"
middle-click-paste = false
indent-guides = { render = true }
soft-wrap = { enable = true }
idle-timeout = 0

[editor.statusline]
right = ["diagnostics", "position", "position-percentage", "file-encoding"]

[editor.lsp]
display-messages = true

[keys.normal]
A-i = ":toggle-option lsp.display-inlay-hints"
