[time]
disabled = false
time_format = "%H:%M"

[[battery.display]]
threshold = 25
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 75
style = "bold green"

[[battery.display]]
threshold = 100
style = "bold blue"
