#!/usr/bin/env bash

default="$(pactl get-default-sink)"

while read -r sink; do
    sink=($sink)
    id="${sink[0]}}";
    name="${sink[1]}"

    [[ "$name" == "$default" || $name =~ "Samson" ]] && continue

    pactl set-default-sink "$id" && echo "switching to $name"
    break
done <<< "$(pactl list short sinks)"
