#!/bin/env python

from glob import glob
import os.path as path
import re

GENSHIN_ROOT = (
    "/home/rezzubs/.local/share/honkers-railway-launcher/HSR/"
)

data_path = glob(
    path.join(
        GENSHIN_ROOT,
        "StarRail_Data/webCaches/*/Cache/Cache_Data/data_2",
    )
)[-1]

with open(data_path, encoding="utf-8", errors="ignore") as file:
    data = file.read()


pattern = r"https:\/\/(?:[a-z\-]+\.?)+\/common\/gacha_record\/api\/getGachaLog\?(?:\w+=(?:\w|\.|\%|-)+\&?)+"

url = re.findall(pattern, data)[-1]

print(url)
