#!/bin/env python

from glob import glob
import os.path as path
import re

GENSHIN_ROOT = (
    "/mnt/data-fast/lutris/genshin-impact/drive_c/Program Files/Genshin Impact/"
)

data_path = glob(
    path.join(
        GENSHIN_ROOT,
        "Genshin Impact game/GenshinImpact_Data/webCaches/*/Cache/Cache_Data/data_2",
    )
)[-1]

with open(data_path, encoding="utf-8", errors="ignore") as file:
    data = file.read()


pattern = r"https:\/\/(?:[a-z\-]+\.?)+\/genshin\/event\/e20190909gacha-v\d\/index.html\?(?:\w+=(?:\w|\.|\%)+\&?)+global"

url = re.findall(pattern, data)[-1]

print(url)
